CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "DisplayName" text NOT NULL,
        "Role" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "BrandProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "CompanyName" text NOT NULL,
        "ContactFullName" text NOT NULL,
        "WebsiteUrl" text,
        "Industry" text NOT NULL,
        "MonthlyBudget" text NOT NULL,
        "ProfilePictureUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BrandProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BrandProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "InfluencerProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "FullName" text NOT NULL,
        "PrimaryPlatform" text NOT NULL,
        "PlatformUsername" text NOT NULL,
        "ContentNiche" text NOT NULL,
        "AudienceSize" text NOT NULL,
        "Verified" boolean NOT NULL,
        "Bio" text,
        "Location" text,
        "WebsiteUrl" text,
        "Followers" integer NOT NULL,
        "EngagementRate" numeric(5,2) NOT NULL,
        "RateNote" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InfluencerProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InfluencerProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "Title" text NOT NULL,
        "Body" text NOT NULL,
        "LinkUrl" text,
        "IsRead" boolean NOT NULL,
        "Category" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Campaigns" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BrandProfileId" integer NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Status" integer NOT NULL,
        "Budget" numeric(12,2) NOT NULL,
        "SpentAmount" numeric(12,2) NOT NULL,
        "Platform" text,
        "Niche" text,
        "Deadline" timestamp with time zone,
        "MediaUrl" text,
        "MediaType" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Campaigns" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Campaigns_BrandProfiles_BrandProfileId" FOREIGN KEY ("BrandProfileId") REFERENCES "BrandProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "ShortlistEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BrandProfileId" integer NOT NULL,
        "InfluencerProfileId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ShortlistEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShortlistEntries_BrandProfiles_BrandProfileId" FOREIGN KEY ("BrandProfileId") REFERENCES "BrandProfiles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ShortlistEntries_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Conversations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CampaignId" integer,
        "BrandProfileId" integer NOT NULL,
        "InfluencerProfileId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Conversations_BrandProfiles_BrandProfileId" FOREIGN KEY ("BrandProfileId") REFERENCES "BrandProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Conversations_Campaigns_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Conversations_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Proposals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CampaignId" integer NOT NULL,
        "InfluencerProfileId" integer NOT NULL,
        "InitiatedBy" integer NOT NULL,
        "ProposedAmount" numeric(12,2) NOT NULL,
        "Deliverables" text NOT NULL,
        "Timeline" text,
        "Message" text,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Proposals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proposals_Campaigns_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proposals_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Messages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ConversationId" integer NOT NULL,
        "SenderUserId" text NOT NULL,
        "Body" text NOT NULL,
        "MediaUrl" text,
        "MediaType" text,
        "SentAt" timestamp with time zone NOT NULL,
        "ReadAt" timestamp with time zone,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_AspNetUsers_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Collaborations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProposalId" integer NOT NULL,
        "CampaignId" integer NOT NULL,
        "InfluencerProfileId" integer NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Collaborations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Collaborations_Campaigns_CampaignId" FOREIGN KEY ("CampaignId") REFERENCES "Campaigns" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Collaborations_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Collaborations_Proposals_ProposalId" FOREIGN KEY ("ProposalId") REFERENCES "Proposals" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Milestones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CollaborationId" integer NOT NULL,
        "Title" text NOT NULL,
        "Description" text,
        "Amount" numeric(12,2) NOT NULL,
        "DueDate" timestamp with time zone,
        "Status" integer NOT NULL,
        "ProofUrl" text,
        "ProofNotes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Milestones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Milestones_Collaborations_CollaborationId" FOREIGN KEY ("CollaborationId") REFERENCES "Collaborations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Disputes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CollaborationId" integer NOT NULL,
        "MilestoneId" integer,
        "BrandProfileId" integer NOT NULL,
        "InfluencerProfileId" integer NOT NULL,
        "Reason" text NOT NULL,
        "Status" integer NOT NULL,
        "ResolutionNotes" text,
        "ResolvedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Disputes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Disputes_BrandProfiles_BrandProfileId" FOREIGN KEY ("BrandProfileId") REFERENCES "BrandProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Disputes_Collaborations_CollaborationId" FOREIGN KEY ("CollaborationId") REFERENCES "Collaborations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Disputes_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Disputes_Milestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES "Milestones" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CollaborationId" integer NOT NULL,
        "MilestoneId" integer,
        "Amount" numeric(12,2) NOT NULL,
        "Status" integer NOT NULL,
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Collaborations_CollaborationId" FOREIGN KEY ("CollaborationId") REFERENCES "Collaborations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Payments_Milestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES "Milestones" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_BrandProfiles_UserId" ON "BrandProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Campaigns_BrandProfileId" ON "Campaigns" ("BrandProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Collaborations_CampaignId" ON "Collaborations" ("CampaignId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Collaborations_InfluencerProfileId" ON "Collaborations" ("InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_Collaborations_ProposalId" ON "Collaborations" ("ProposalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Conversations_BrandProfileId" ON "Conversations" ("BrandProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Conversations_CampaignId" ON "Conversations" ("CampaignId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Conversations_InfluencerProfileId" ON "Conversations" ("InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Disputes_BrandProfileId" ON "Disputes" ("BrandProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Disputes_CollaborationId" ON "Disputes" ("CollaborationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Disputes_InfluencerProfileId" ON "Disputes" ("InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Disputes_MilestoneId" ON "Disputes" ("MilestoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_InfluencerProfiles_UserId" ON "InfluencerProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Messages_SenderUserId" ON "Messages" ("SenderUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Milestones_CollaborationId" ON "Milestones" ("CollaborationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Payments_CollaborationId" ON "Payments" ("CollaborationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Payments_MilestoneId" ON "Payments" ("MilestoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Proposals_CampaignId" ON "Proposals" ("CampaignId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_Proposals_InfluencerProfileId" ON "Proposals" ("InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_ShortlistEntries_BrandProfileId_InfluencerProfileId" ON "ShortlistEntries" ("BrandProfileId", "InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    CREATE INDEX "IX_ShortlistEntries_InfluencerProfileId" ON "ShortlistEntries" ("InfluencerProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916061554_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260916061554_InitialPostgres', '10.0.11');
    END IF;
END $EF$;
COMMIT;

