using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brandora.Web.Migrations
{
    /// <inheritdoc />
    public partial class PaymentGatewaySchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Written idempotently (IF NOT EXISTS): this schema was applied to the shared
            // database by hand before the migration was recorded in __EFMigrationsHistory,
            // so `dotnet ef database update` must be able to run it over a database that
            // already has some or all of these objects, and simply record it.
            migrationBuilder.Sql("""
                ALTER TABLE "Payments" ADD COLUMN IF NOT EXISTS "GatewayPaymentId" text;
                ALTER TABLE "Payments" ADD COLUMN IF NOT EXISTS "NetAmount" numeric(12,2) NOT NULL DEFAULT 0.0;
                ALTER TABLE "Payments" ADD COLUMN IF NOT EXISTS "PlatformFeeAmount" numeric(12,2) NOT NULL DEFAULT 0.0;
                ALTER TABLE "Milestones" ADD COLUMN IF NOT EXISTS "BrandApprovedAt" timestamp with time zone;
                ALTER TABLE "Milestones" ADD COLUMN IF NOT EXISTS "BrandRevisionReason" text;

                CREATE TABLE IF NOT EXISTS "PaymentAttempts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PaymentId" integer NOT NULL,
                    "Gateway" text NOT NULL,
                    "GatewayPaymentId" text,
                    "GatewayTransactionId" text,
                    "Status" integer NOT NULL,
                    "FailureReason" text,
                    "CreateResponseJson" text,
                    "ExecuteResponseJson" text,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "CompletedAt" timestamp with time zone,
                    CONSTRAINT "PK_PaymentAttempts" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PaymentAttempts_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "WalletTransactions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "InfluencerProfileId" integer NOT NULL,
                    "Type" integer NOT NULL,
                    "Amount" numeric(12,2) NOT NULL,
                    "PaymentId" integer,
                    "Description" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_WalletTransactions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_WalletTransactions_InfluencerProfiles_InfluencerProfileId" FOREIGN KEY ("InfluencerProfileId") REFERENCES "InfluencerProfiles" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_WalletTransactions_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_PaymentAttempts_PaymentId" ON "PaymentAttempts" ("PaymentId");
                CREATE INDEX IF NOT EXISTS "IX_WalletTransactions_InfluencerProfileId" ON "WalletTransactions" ("InfluencerProfileId");
                CREATE INDEX IF NOT EXISTS "IX_WalletTransactions_PaymentId" ON "WalletTransactions" ("PaymentId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PaymentAttempts");

            migrationBuilder.DropTable(
                name: "WalletTransactions");

            migrationBuilder.DropColumn(
                name: "GatewayPaymentId",
                table: "Payments");

            migrationBuilder.DropColumn(
                name: "NetAmount",
                table: "Payments");

            migrationBuilder.DropColumn(
                name: "PlatformFeeAmount",
                table: "Payments");

            migrationBuilder.DropColumn(
                name: "BrandApprovedAt",
                table: "Milestones");

            migrationBuilder.DropColumn(
                name: "BrandRevisionReason",
                table: "Milestones");
        }
    }
}
